import saveAs from 'file-saver';
import { WorksheetData } from '../types';

export const downloadAsHwp = (data: WorksheetData) => {
  const contentHtml = `
<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="utf-8">
<title>${data.movieTitle} 학습지</title>
<style>
  body { font-family: 'Malgun Gothic', 'Batang', serif; line-height: 1.6; }
  h1 { font-size: 24pt; color: #1e3a8a; text-align: center; margin-bottom: 20px; }
  h2 { font-size: 16pt; color: #1e40af; border-bottom: 2px solid #1e40af; padding-bottom: 5px; margin-top: 20px; }
  h3 { font-size: 14pt; color: #333; margin-top: 15px; }
  p { font-size: 11pt; text-align: justify; }
  .info-box { border: 1px solid #ccc; padding: 15px; background-color: #f9f9f9; margin-bottom: 20px; }
  .info-item { margin-bottom: 5px; }
  .question-box { background-color: #eff6ff; padding: 15px; border-radius: 5px; margin-bottom: 10px; }
  .activity-area { border: 1px dashed #999; padding: 20px; min-height: 100px; margin-top: 10px; }
  ul { margin-top: 5px; }
  li { margin-bottom: 5px; }
</style>
</head>
<body>

  <h1>🎬 영화 감상 학습지: ${data.movieTitle}</h1>

  <div class="info-box">
    <div class="info-item"><strong>감독:</strong> ${data.director}</div>
    <div class="info-item"><strong>개봉:</strong> ${data.releaseYear}</div>
    <div class="info-item"><strong>장르:</strong> ${data.genre}</div>
    <div class="info-item"><strong>등급:</strong> ${data.ageRating}</div>
  </div>

  <h2>📝 줄거리 요약</h2>
  <p>${data.plotSummary}</p>

  <h2>🎓 교육적 주제</h2>
  <ul>
    ${data.educationalThemes.map(theme => `<li>${theme}</li>`).join('')}
  </ul>

  <h2>💬 토론 질문</h2>
  ${data.discussionQuestions.map((q, i) => `
    <div class="question-box">
      <strong>Q${i + 1}.</strong> ${q}
    </div>
  `).join('')}

  <h2>✍️ 활동: ${data.activityContent ? '심화 학습' : '활동'}</h2>
  <div>
    ${
      // Convert basic markdown-like structure to HTML manually for simplicity in this utility
      // Ideally we would use a library, but basic replacement works for generated simple markdown
      data.activityContent
        .replace(/\n/g, '<br/>')
        .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
        .replace(/### (.*?)(<br\/>|$)/g, '<h3>$1</h3>')
        .replace(/## (.*?)(<br\/>|$)/g, '<h3>$1</h3>')
        .replace(/- (.*?)(<br\/>|$)/g, '• $1<br/>')
    }
  </div>

  <br/><br/>
  <p style="text-align: center; color: #888; font-size: 10pt;">Generated by CineEdu AI</p>

</body>
</html>
  `;

  const blob = new Blob([contentHtml], { type: "application/x-hwp;charset=utf-8" });
  saveAs(blob, `${data.movieTitle}_학습지.hwp`);
};
